language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mongodb

php:
  - 7.2

before_script:
  - composer install --no-interaction
  - cp phpunit.dist.xml phpunit.xml

script:
  - vendor/bin/phpunit
